Project/Elifx-Mvc/PCar/Areas/Administrator/Models/MailConfig.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PCar.Areas.Administrator.Models
{
    public class MailConfig
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập Port")]
        public int Port { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Vui lòng nhập email")]
        [EmailAddress(ErrorMessage = "Vui lòng nhập đúng địa chỉ email")]
        public string Email { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Smtp")]
        [Required(ErrorMessage = "Vui lòng nhập host")]
        public string Smtp { get; set; }
    }
}

Project/Elifx-Mvc/PCar/Areas/Administrator/Controllers/MailConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLibrary.Database;
using DataLibrary.Security;

namespace PCar.Areas.Administrator.Controllers
{
    public class MailConfigController : IBaseController
    {
        //
        // GET: /Administrator/MailConfig/

        public ActionResult Index()
        {
            if (TempData["Messages"] != null)
            {
                ViewBag.Messages = TempData["Messages"];
            }
            ViewBag.Title = "Cấu hình Email";
            return View();
        }
        [HttpPost]
        public JsonResult List(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                using (var db = new MyDbDataContext())
                {
                    var list = db.MailConfigs.ToList();
                    //Return result to jTable
                    return Json(new { Result = "OK", Records = list, TotalRecordCount = list.Count });
                }

            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Create(MailConfig model)
        {
            using (var db = new MyDbDataContext())
            {
                if (db.MailConfigs.Any())
                {
                    return Json(new { Result = "ERROR", Message = "Website chỉ được phép tồn tại 1 bản cấu hình" });
                }
                if (ModelState.IsValid)
                {
                    try
                    {
                        MailConfig configWebsite = new MailConfig()
                        {
                            Smtp = model.Smtp,
                            Port = model.Port,
                            Email = model.Email,
                            Password = CryptorEngine.Encrypt(model.Password, true),
                        };
                        db.MailConfigs.InsertOnSubmit(configWebsite);
                        db.SubmitChanges();

                        model.ID = configWebsite.ID;
                        return Json(new { Result = "OK", Message = "Thêm thành công", Record = model });
                    }
                    catch (Exception exception)
                    {
                        return Json(new { Result = "ERROR", Message = "Fail. Error:" + exception.Message });
                    }
                }
                return Json(new { Result = "ERROR", Errors = "Error", Message = "Dữ liệu đầu vào không đúng định dạng" });
            }
        }

        [HttpPost]
        public JsonResult Edit(MailConfig model)
        {
            using (var db = new MyDbDataContext())
            {


                try
                {
                    var edit = db.MailConfigs.FirstOrDefault(b => b.ID == model.ID);
                    if (edit != null)
                    {
                        edit.Port = model.Port;
                        edit.Email = model.Email;
                        edit.Password = CryptorEngine.Encrypt(model.Password, true);
                        edit.Smtp = model.Smtp;

                        db.SubmitChanges();

                        return Json(new { Result = "OK", Message = "Sửa thành công", Record = model });
                    }
                    else
                    {
                        return Json(new { Result = "ERROR", Message = "Bản ghi không tồn tại" });
                    }
                }
                catch (Exception exception)
                {
                    return Json(new { Result = "ERROR", Message = "Fail. Error:" + exception.Message });
                }
            }

        }

    }
}

Project/Elifx-Mvc/PCar/Areas/Administrator/Views/MailConfig/Index.cshtml
@model  PCar.Areas.Administrator.Models.MailConfig
@{
    Layout = "~/Areas/Administrator/Views/Shared/_LayoutAdmin.cshtml";
}

@section styles
{

    <!-- DataTables -->
    @*<link rel="stylesheet" href="~/Assets/Admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">*@
    <link href="~/Scripts/jquery-ui-1.11.0/jquery-ui.css" rel="stylesheet" />
    <link href="~/Scripts/jtable/themes/metro/lightgray/jtable.min.css" rel="stylesheet" />
    <link href="~/Scripts/jtable/themes/jqueryui/jtable_jqueryui.css" rel="stylesheet" />

}
<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-edit"></i>
                    Quản lý cấu hình email
                </h3>
            </div>
            <div class="card-body pad table-responsive">
                <div id="jtable-main-container"></div>
            </div>
            <!-- /.card -->
        </div>
    </div>
    <!-- /.col -->
</div>
@section scripts
{
    <script type="text/javascript">
    $(document).ready(function () {
        $('#jtable-main-container').jtable({
                        title: '@ViewBag.Title',
            paging: true, //Enable paging
            pageSize: 20, //Set page size (default: 10)
            sorting: true, //Enable sorting
            selecting: true, //Enable selecting
            multiselect: true, //Allow multiple selecting
            selectingCheckboxes: true, //Show checkboxes on first column
            columnResizable: false, //Actually, no need to set true since it's default
            columnSelectable: true, //Actually, no need to set true since it's default
            saveUserPreferences: false, //Actually, no need to set true since it's default

            actions: {
                listAction: '@Url.Action("List", "MailConfig")',
                createAction: '@Url.Action("Create", "MailConfig")',
                updateAction: '@Url.Action("Edit", "MailConfig")',
            },
            fields: {
                ID: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },

                Email: {
                    title: '@Html.DisplayNameFor(c=>c.Email)<span class="asteriskjs">*</span>',
                    sorting: false,
                    width: '20%',
                },
                Port: {
                    title: '@Html.DisplayNameFor(c=>c.Port)<span class="asteriskjs">*</span>',
                    sorting: false,
                    width: '20%',
                },
                Password: {
                    title: '@Html.DisplayNameFor(c=>c.Password)<span class="asteriskjs">*</span>',
                    list: true,
                    width: '20%',
                    type: 'password'
                },
                Smtp: {
                    title: '@Html.DisplayNameFor(c=>c.Smtp)<span class="asteriskjs">*</span>',
                    sorting: false,
                    width: '20%',
                },

            }
        });
        //Load data
        $('#jtable-main-container').jtable('load');
    });

    </script>
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.9.2.js"></script>
    <script src="~/Scripts/jtable/jquery.jtable.js"></script>

}